apiVersion: v1
entries:
  postgres-operator:
  - apiVersion: v1
    appVersion: 1.6.0
    created: "2020-12-17T15:46:21.948364251+01:00"
    description: Postgres Operator creates and manages PostgreSQL clusters running
      in Kubernetes
    digest: de1306a53dd8264a2703fe0867b43a13b1e378e6d81f6200ecdea1c8ef9d202d
    home: https://github.com/zalando/postgres-operator
    keywords:
    - postgres
    - operator
    - cloud-native
    - patroni
    - spilo
    maintainers:
    - email: opensource@zalando.de
      name: Zalando
    name: postgres-operator
    sources:
    - https://github.com/zalando/postgres-operator
    urls:
    - postgres-operator-1.6.0.tgz
    version: 1.6.0
  - apiVersion: v1
    appVersion: 1.5.0
    created: "2020-12-17T15:46:21.945665932+01:00"
    description: Postgres Operator creates and manages PostgreSQL clusters running
      in Kubernetes
    digest: 198351d5db52e65cdf383d6f3e1745d91ac1e2a01121f8476f8b1be728b09531
    home: https://github.com/zalando/postgres-operator
    keywords:
    - postgres
    - operator
    - cloud-native
    - patroni
    - spilo
    maintainers:
    - email: opensource@zalando.de
      name: Zalando
    name: postgres-operator
    sources:
    - https://github.com/zalando/postgres-operator
    urls:
    - postgres-operator-1.5.0.tgz
    version: 1.5.0
generated: "2020-12-17T15:46:21.937893219+01:00"
