apiVersion: v1
entries:
  postgres-operator-ui:
  - apiVersion: v1
    appVersion: 1.6.0
    created: "2021-02-19T12:15:41.102835119+01:00"
    description: Postgres Operator UI provides a graphical interface for a convenient database-as-a-service user experience
    digest: 47d61aa9bc650916c2f6ac5a6d4425d4b7c2c9dbc3bac16d07038fd7ca60e601
    home: https://github.com/zalando/postgres-operator
    keywords:
    - postgres
    - operator
    - ui
    - cloud-native
    - patroni
    - spilo
    maintainers:
    - email: opensource@zalando.de
      name: Zalando
    name: postgres-operator-ui
    sources:
    - https://github.com/zalando/postgres-operator
    urls:
    - postgres-operator-ui-1.6.0.tgz
    version: 1.6.0
generated: "2021-02-19T12:15:41.102102102+01:00"
