name: ubuntu

on: 
  pull_request:
  push:
    branches:
    - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Make dependencies
      run: make deps
    - name: Compile
      run: make linux
    - name: Run unit tests
      run: make test
    - name: Run end-2-end tests
      run: make e2e
